- hosts: all
  roles:
    - common
  tasks:

    - ansible.builtin.debug:
       var: ansible_facts
      tags:
      - never

    - ansible.builtin.shell:
        cmd: cat /tmp/readme.txt
        
  